defaults:
  - _self_

exp_name: "portugal-wildfire-pre-post_02"

id_ood_disaster: [{"disaster_name": "portugal-wildfire", "pre-post": "pre"}, {"disaster_name": "portugal-wildfire", "pre-post": "post"}]

paths:
  root: "/data/dataood/xview2/"
  default_root_dir: "experiments"

dataset:
  checksum: false

training:
  batch_size: 32
  val_split_pct: 0.2
  max_epochs: 25
  min_epochs: 1
  early_stopping_patience: 5
  random_crop: 256
  devices: 1
  patience: 5
  pin_memory: False
  persistent_workers: False
  num_workers: 8
  device: 'cuda'

model:
  type: "unet"
  backbone: "resnet50"
  weights: true
  in_channels: 3
  num_classes: 2
  lr: 0.001
  task_patience: 5
  freeze_backbone: True
  freeze_decoder: False

logging:
  path: ./geospatial-ood-detection/experiments
