defaults:
  - _self_

exp_name: Holdout_Residential_resnet50_0066

model:
  name: resnet50
  weights: true
  in_channels: 13
  num_classes: 9
  loss: ce
  lr: 0.0001
  patience: 5

trainer: 
  devices: 1
  fast_dev_run: false
  min_epochs: 1
  max_epochs: 50

data:
  class_name: Residential
  root: "/home/t-burakekim/ssdprivate/eurosat_holdout_residential"
  batch_size: 64
  num_workers: 8
  exclude_class: Residential
  download: true
  checksum: true

logging:
  path: /home/t-burakekim/azurefiles/geospatial-ood-detection/experiments

training:
  patience: 5