defaults:
  - _self_

exp_name: Holdout_SeaLake_resnet50_0066

model:
  name: resnet50
  weights: true
  in_channels: 13
  num_classes: 9
  loss: ce
  lr: 0.0001
  patience: 5

trainer: 
  devices: 1
  fast_dev_run: false
  min_epochs: 1
  max_epochs: 50

data:
  class_name: SeaLake
  root: "/data/dataood/eurosat_holdout_datasets/eurosat_holdout_SeaLake"
  batch_size: 64
  num_workers: 8
  download: true
  checksum: false
  drop_last: false

logging:
  path: ./geospatial-ood-detection/experiments

training:
  patience: 5